---
abstract: ~
author:
  - 'Yuji Shimada <xaicron@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-Unicode
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Spec: 0
  Win32API::File: 0
  XSLoader: 0.1
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/xaicron/p5-win32-unicode.git
version: 0.20
