---
abstract: 'perl unicode-friendly wrapper for win32api.'
author:
  - 'Yuji Shimada <xaicron@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-Unicode
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Win32API::File: 0.1101
  XSLoader: 0.02
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/xaicron/p5-win32-unicode
version: 0.26
